### ISSUE TITLE
Use from Storyboard

### ISSUE THREAD

**Issue by dimohamdy** [seedco/StackViewController#21]
add feature to use it from Storyboard

**Comment by indragiek** [comment]
Anything in particular you're looking for? You can already create instances of `StackViewContainer` and `StackViewController` inside a storyboard, but they need to be configured in code. Are you looking for configuration support from within Interface Builder?

**Comment by dimohamdy** [comment]
yes

**Comment by indragiek** [comment]
Which configurable properties did you want? I don't think there are many properties that could be set up to be configurable using the capabilities that `IBDesignable` currently provides.

**Comment by indragiek** [comment]
Closing this for now. I can reopen it if there are particular requests for properties that will work with `IBDesignable`.
