### ISSUE TITLE
Auto expand rows

### ISSUE THREAD

**Issue by GJNilsen** [seedco/StackViewController#24]
When running the app on iPhone 6, after adding the third picture, it should be on a line below, instead of scrolling off to the side. The same way the text entry field expands downwards, the container of the cells should also expand accordingly.
(BTW, fantastic work done on the StackViewController)

**Comment by jessedc** [comment]
The demo app's implementation (`ImageAttachmentView`) uses a UIStackView to lay out the thumbnail images horizontally and UIStackView is limited to a single row or column. 

Laying the thumbnails out in a single line is a limitation of a stack view, not a bug with the project. 

From [Apple's docs on UIStackView](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIStackView_Class_Reference/):

> The UIStackView class provides a streamlined interface for laying out a collection of views in either a column or a row

**Comment by indragiek** [comment]
@GJNilsen This was intentional, as explained by @jessedc (thanks!)
