### ISSUE TITLE
removeContentViewAtIndex doesn't actually remove the UIView from the superview

### ISSUE THREAD

**Issue by tankadesign** [seedco/StackViewController#31]
stackView.removeArrangedSubview does not actually remove the subview from its superview. This leaves a big pile of UIViews sitting around on screen afterwards.

This will fix it:
    open func removeContentViewAtIndex(_ index: Int) {
        precondition(index >= items.startIndex)
        precondition(index < items.endIndex)
        
        let item = items[index]
        if items.count >= 1 && index == (items.endIndex - 1) && index > 0 {
            let previousItem = items[(index - 1)]
            if let separatorView = previousItem.separatorView {
                stackView.removeArrangedSubview(separatorView)
                separatorView.removeFromSuperview()
                previousItem.separatorView = nil
            }
        }
        stackView.removeArrangedSubview(item.contentView)
        item.contentView.removeFromSuperview()
        if let separatorView = item.separatorView {
            stackView.removeArrangedSubview(separatorView)
            separatorView.removeFromSuperview()
        }
        items.remove(at: index)
        _contentViews.remove(at: index)
    }

**Comment by klaaspieter** [comment]
Resolved by #29.
