### ISSUE TITLE
Podspec / Release out of date

### ISSUE THREAD

**Issue by traylewin** [seedco/StackViewController#32]
Hi there. Love this project and the quality of the code! Can you do us a favor and release a new version with the latest changes? The current podspec and release tags cause an older version of the code to be installed (pre Swift 3) Thanks!

**Comment by mergesort** [comment]
Bumping this request. I can make the new podspec if you'd like @klaaspieter?

**Comment by klaaspieter** [comment]
#33 should do it. I'll push it when I get pod trunk access.
