### ISSUE TITLE
WKWebView as StackViewController item

### ISSUE THREAD

**Issue by giofid** [seedco/StackViewController#39]
Hi,
I am currently considering to use this good library in my project to show user inbox email. So, in the Demo App, I'm trying to add a `WKWebView` as `StackViewController` item in place of `UITextView` but web view is not shown. This's modified `setupStackViewController` method:
```
import WKWebKit

....

fileprivate func setupStackViewController() {
     let toFieldController = LabeledTextFieldController(labelText: "To:")
     firstField = toFieldController.view
     stackViewController.addItem(toFieldController)
     stackViewController.addItem(LabeledTextFieldController(labelText: "Subject:"))
        
     let webView = WKWebView()
     webView.loadHTMLString("This field automatically expands as you type, no additional logic required", baseURL: nil)
     webView.scrollView.isScrollEnabled = false
     stackViewController.addItem(webView, canShowSeparator: false)
        
     stackViewController.addItem(ImageAttachmentViewController())
 }
```
**Debug View Hierarchy** tells me _Scrollable content size is ambiguous_. 
What I'm doing wrong?

Thanks for your help,
Giorgio

**Comment by klaaspieter** [comment]
Sorry for the slow response. It looks like `WKWebView` has no intrinsic height. If you want it to become visible in the stack you'll need to manually set a height using something like `webView.heightAnchor.constraint(equalToConstant: 200).isActive = true`.

Closing this, feel free to re-open if the problem persists.
